[package]
name = "supertoml"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }

[[bin]]
name = "supertoml"
path = "src/main.rs"

[lib]
name = "supertoml"
path = "src/lib.rs"
