name: Build and Test

on:
  workflow_call:
    inputs:
      upload_artifacts:
        description: "Whether to upload artifacts to GitHub"
        required: false
        default: false
        type: boolean
    outputs:
      version:
        description: "The version extracted from Cargo.toml"
        value: ${{ jobs.extract-version.outputs.version }}

env:
  CARGO_TERM_COLOR: always

jobs:
  extract-version:
    name: Extract Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.cargo_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from Cargo.toml
        id: cargo_version
        run: |
          VERSION=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[0].version')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

  build:
    name: Build for ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    needs: extract-version
    strategy:
      matrix:
        include:
          # macOS
          - os: macos-latest
            arch: darwin-amd64
            target: x86_64-apple-darwin
            packaging:
              - homebrew
              - mise
              - asdf
          - os: macos-latest
            arch: darwin-arm64
            target: aarch64-apple-darwin
            packaging:
              - homebrew
              - mise
              - asdf

          # Linux
          - os: ubuntu-latest
            arch: linux-amd64
            target: x86_64-unknown-linux-gnu
            packaging:
              - apt
              - yum
              - pacman
              - mise
              - asdf
          - os: ubuntu-24.04-arm
            arch: linux-arm64
            target: aarch64-unknown-linux-gnu
            packaging:
              - apt
              - yum
              - pacman
              - mise
              - asdf
          - os: ubuntu-latest
            arch: linux-386
            target: i686-unknown-linux-gnu
            packaging:
              - apt
              - yum
              - pacman
              - mise
              - asdf

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cross-compilation dependencies
        if: matrix.target == 'i686-unknown-linux-gnu' || matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          if [[ "${{ matrix.target }}" == "i686-unknown-linux-gnu" ]]; then
            # Install multilib for i686 cross-compilation
            sudo apt-get install -y gcc-multilib
          elif [[ "${{ matrix.target }}" == "x86_64-unknown-linux-gnu" ]]; then
            # Install x86_64 cross-compilation tools
            sudo apt-get install -y gcc-x86-64-linux-gnu
          fi

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build release binary
        shell: bash
        run: |
          # Set up cross-compilation environment for cross-compiled targets
          if [[ "${{ matrix.target }}" == "i686-unknown-linux-gnu" ]]; then
            export CC_i686_unknown_linux_gnu=gcc
            export CXX_i686_unknown_linux_gnu=g++
            export CFLAGS_i686_unknown_linux_gnu="-m32"
            export CXXFLAGS_i686_unknown_linux_gnu="-m32"
            export CARGO_TARGET_I686_UNKNOWN_LINUX_GNU_LINKER=gcc
          elif [[ "${{ matrix.target }}" == "x86_64-unknown-linux-gnu" ]]; then
            export CC_x86_64_unknown_linux_gnu=x86_64-linux-gnu-gcc
            export CXX_x86_64_unknown_linux_gnu=x86_64-linux-gnu-g++
            export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc
          fi
          cargo build --release --target ${{ matrix.target }}
          # Strip debug symbols to reduce binary size
          if [[ "${{ runner.os }}" != "Windows" ]]; then
            strip target/${{ matrix.target }}/release/supertoml
          fi

      - name: Package binary
        if: inputs.upload_artifacts
        shell: bash
        run: |
          # Create packages directory
          mkdir -p packages

          # Create both zip and tar.gz packages for all platforms
          echo "Creating packages for: ${{ matrix.arch }} v${{ needs.extract-version.outputs.version }}"

          # Create zip package
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            # Use PowerShell for Windows
            powershell -Command "Compress-Archive -Path 'target/${{ matrix.target }}/release/supertoml.exe' -DestinationPath 'packages/supertoml-${{ needs.extract-version.outputs.version }}-${{ matrix.arch }}.zip' -Force"
          else
            # Use zip for Unix systems
            zip -j "packages/supertoml-${{ needs.extract-version.outputs.version }}-${{ matrix.arch }}.zip" "target/${{ matrix.target }}/release/supertoml"
          fi

          # Create tar.gz package
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            # Use tar (available on Windows 10+ and GitHub runners)
            tar -czf "packages/supertoml-${{ needs.extract-version.outputs.version }}-${{ matrix.arch }}.tar.gz" -C "target/${{ matrix.target }}/release" supertoml.exe
          else
            tar -czf "packages/supertoml-${{ needs.extract-version.outputs.version }}-${{ matrix.arch }}.tar.gz" -C "target/${{ matrix.target }}/release" supertoml
          fi

          echo "Created packages:"
          ls -la packages/

      - name: Run tests
        shell: bash
        run: |
          # Set up cross-compilation environment for cross-compiled targets
          if [[ "${{ matrix.target }}" == "i686-unknown-linux-gnu" ]]; then
            export CC_i686_unknown_linux_gnu=gcc
            export CXX_i686_unknown_linux_gnu=g++
            export CFLAGS_i686_unknown_linux_gnu="-m32"
            export CXXFLAGS_i686_unknown_linux_gnu="-m32"
            export CARGO_TARGET_I686_UNKNOWN_LINUX_GNU_LINKER=gcc
          elif [[ "${{ matrix.target }}" == "x86_64-unknown-linux-gnu" ]]; then
            export CC_x86_64_unknown_linux_gnu=x86_64-linux-gnu-gcc
            export CXX_x86_64_unknown_linux_gnu=x86_64-linux-gnu-g++
            export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc
          fi

          cargo test --target ${{ matrix.target }}

      - name: Run clippy
        shell: bash
        run: |
          # Set up cross-compilation environment for cross-compiled targets
          if [[ "${{ matrix.target }}" == "i686-unknown-linux-gnu" ]]; then
            export CC_i686_unknown_linux_gnu=gcc
            export CXX_i686_unknown_linux_gnu=g++
            export CFLAGS_i686_unknown_linux_gnu="-m32"
            export CXXFLAGS_i686_unknown_linux_gnu="-m32"
            export CARGO_TARGET_I686_UNKNOWN_LINUX_GNU_LINKER=gcc
          elif [[ "${{ matrix.target }}" == "x86_64-unknown-linux-gnu" ]]; then
            export CC_x86_64_unknown_linux_gnu=x86_64-linux-gnu-gcc
            export CXX_x86_64_unknown_linux_gnu=x86_64-linux-gnu-g++
            export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc
          fi

          cargo clippy --target ${{ matrix.target }} -- -D warnings

      - name: Check formatting
        if: runner.os != 'Windows' # Only run once, avoid Windows line ending issues
        run: cargo fmt -- --check

      - name: Test release binary
        shell: bash
        run: |
          # Test the actual release binary that will be uploaded
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            # Windows binary
            ./target/${{ matrix.target }}/release/supertoml.exe --help
            echo '[test]' > test.toml
            echo 'value = "hello"' >> test.toml
            echo 'number = 42' >> test.toml
            ./target/${{ matrix.target }}/release/supertoml.exe test.toml test
          else
            # Unix-like systems (macOS, Linux)
            ./target/${{ matrix.target }}/release/supertoml --help
            echo '[test]' > test.toml
            echo 'value = "hello"' >> test.toml
            echo 'number = 42' >> test.toml
            ./target/${{ matrix.target }}/release/supertoml test.toml test
          fi

      - name: Upload artifact
        if: inputs.upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: packages/
          exclude: "*.d *.pdb"
