name: Pre-merge Checks

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    name: Pre-commit Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

  build-and-test:
    name: Build and Test All Platforms
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      contents: read
