name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    uses: ./.github/workflows/build-and-test.yml
    with:
      create_release: true
      draft_release: true
    permissions:
      contents: write
